### ISSUE TITLE
Dependabot: Invalid ignore condition (version range) specified for "oldstable" image

### ISSUE THREAD

**Issue by atc0005** [atc0005/go-ci#100]
Suggested fix from GH user jurre:

```diff
    ignore:
      - dependency-name: "golang"
-       versions: ["1.15.x"]
+       versions: ["1.15"]
```

refs https://github.com/dependabot/dependabot-core/issues/2644#issuecomment-709212848

**Comment by atc0005** [comment]
See also GH-97.

**Comment by atc0005** [comment]
Still not resolved.

However, I saw this syntax in an automated PR for another project that I'm watching:

```yaml
  ignore:
  - dependency-name: openjdk
    versions:
    - ">= 11.pre.jre.pre.slim.a"
    - "< 12"
```

Perhaps the same upper/lower bounds can be specified here?

refs https://github.com/Graylog2/graylog-docker/blob/6d5293342f846b347fe07a4841369e8d47c7cd3e/.github/dependabot.yml
