### ISSUE TITLE
golangci-lint | Enable gocyclo, gocognit linters

### ISSUE THREAD

**Issue by atc0005** [atc0005/go-ci#62]
Relevant portion of the configuration currently used by the `atc0005/go-teams-notify` project (inherited from the dasrick/go-teams-notify project):

```yaml
linters:
  enable:
    - gocognit
    - gocyclo

linters-settings:
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10

  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
```
